import products
import store

home_despot = Store("Home_Despot")
lamp = Product("Amazing Lamp", 200, "Lighting")
speakers = Product("Crappy speakers", 50, "Audio")
couch = Product("Comfy Couch", 500, "Furniture")
home_despot.add_product(lamp)
home_despot.add_product(speakers)
home_despot.add_product(couch)
home_despot.products_list[0].print_info()
home_despot.products_list[1].print_info()
home_despot.products_list[2].print_info()
couch.update_price(.1, False)
couch.print_info()
home_despot.sell_product(1)
home_despot.products_list[0].print_info()
home_despot.products_list[1].print_info()
home_despot.inflation(.5)
home_despot.products_list[0].print_info()
home_despot.products_list[1].print_info()
home_despot.set_clearance("Lighting", .8)
home_despot.products_list[1].print_info()
home_despot.products_list[0].print_info()
